name: 🚀 Deploy React App to FTP Server

# Trigger the workflow on push to the main branch
on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy to FTP
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    # Step 2: Set up Node.js environment for React
    - name: 🔧 Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Step 3: Navigate to the 'dileep' directory, install dependencies, and build the project
    - name: 🛠 Install dependencies and build
      run: |
        cd dileep
        npm install
        npm run build

    # Step 4: Deploy the 'dileep/build' folder to FTP server
    - name: 📂 Deploy files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.samkirkland.com
        username: ${{secrets.myFtpUserName}}
        password: ${{ secrets.ftp_password }}
        local-dir: dileep/build/ # Points to the React build folder in 'dileep'
        server-dir: / # Change this to the desired directory on the FTP server
        method: ftp # or ftps if using a secure connection
